## Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[2,3,54,4,5]],np.int32)

In [3]:
myarr[0,1]

3

In [4]:
myarr.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 2, 45, 54,  4,  5]], dtype=int32)

## Array creation: Conversion from other python structures

In [8]:
listarray = np.array([[1,2,3,4,],[5,8,9,5],[0,3,1,5]])

In [9]:
listarray

array([[1, 2, 3, 4],
       [5, 8, 9, 5],
       [0, 3, 1, 5]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 4)

In [12]:
listarray.size

12

In [13]:
np.array({1,2,76,87})

array({1, 2, 76, 87}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng=np.arange(5)

In [17]:
rng

array([0, 1, 2, 3, 4])

In [18]:
lspace = np.linspace(1,5,4)

In [19]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[9.64187289e-317, 0.00000000e+000, 6.91064047e-310,
        6.91064047e-310, 6.91064047e-310, 6.91064047e-310],
       [6.91064047e-310, 6.91064062e-310, 6.91064061e-310,
        6.91064062e-310, 6.91064061e-310, 6.91064047e-310],
       [6.91064047e-310, 6.91064047e-310, 6.91064061e-310,
        6.91064047e-310, 6.91064047e-310, 6.91064047e-310],
       [6.91064047e-310, 6.91064047e-310, 6.91064047e-310,
        6.91064063e-310, 6.91064062e-310, 6.91064051e-310]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr =arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr=arr.ravel()

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.shape

(99,)

In [34]:
x = [[1,2,3,],[2,1,5],[5,1,5],np.int32]

In [35]:
ar = np.array(x)

/tmp/ipykernel_3100/3709845610.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array(x)


In [36]:
ar

array([list([1, 2, 3]), list([2, 1, 5]), list([5, 1, 5]),
       <class 'numpy.int32'>], dtype=object)

In [37]:
ar.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
ar

In [ ]:
for item in ar.flat:
    print(item)

In [ ]:
ar.ndim

In [ ]:
ar.size

In [ ]:
ar.nbytes

In [ ]:
one= np.array([1,3,4,634,2])

In [ ]:
one.argmax()

In [ ]:
one.argmin()

In [ ]:
one.argsort()

In [ ]:
ar

In [ ]:
ar.argmin()

In [ ]:
ar.argmax()

In [ ]:
ar.argmax(axis=1)

In [ ]:
ar

In [ ]:
ar.argsort(axis=1)

In [ ]:
ar.ravel()

In [ ]:
ar.reshape((9,1))

In [ ]:
ar

In [ ]:
ar2 = np.array([[1, 5, 7],
       [2, 1, 6],
       [6, 1, 9]])

In [ ]:
ar + ar2

In [ ]:
ar

In [ ]:
ar2

In [ ]:
ar*ar2

In [ ]:
np.sqrt(ar)

In [ ]:
np.where(ar>3)

In [ ]:
ar

In [ ]:
np.count_nonzero(ar)

In [ ]:
np.nonzero(ar)

In [ ]:
ar[0,2]= 0

In [ ]:
ar

In [ ]:
ar[2,0]= 0

In [ ]:
ar

In [ ]:
np.nonzero(ar)

In [ ]:
import sys

In [ ]:
py_ar = [0,4,55,2]

In [ ]:
np_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)

In [ ]:
np_ar.itemsize * np_ar.size